"""Sepolia adapter for the deployed ClaimsRegistry contract."""

from __future__ import annotations

import json
import os
import re
import threading
from dataclasses import dataclass
from pathlib import Path

from web3 import Web3
from web3.exceptions import Web3RPCError


SEPOLIA_CHAIN_ID = 11_155_111
DEFAULT_MODULE_ID = "ClaimsRegistryModule#ClaimsRegistry"
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_IGNITION_DIR = (
    PROJECT_ROOT / "contract" / "ignition" / "deployments" / "chain-11155111"
)


class BlockchainSubmissionError(RuntimeError):
    """Raised when a claim cannot be committed to the registry."""


@dataclass(frozen=True)
class ChainSubmission:
    claim_id: int
    transaction_hash: str
    block_number: int


def _hex(value: object) -> str:
    encoded = value.hex()  # type: ignore[union-attr]
    return encoded if encoded.startswith("0x") else f"0x{encoded}"


def load_deployment(
    ignition_dir: Path, module_id: str = DEFAULT_MODULE_ID
) -> tuple[str, list[dict[str, object]]]:
    """Load the address and ABI generated by Hardhat Ignition."""

    try:
        addresses = json.loads((ignition_dir / "deployed_addresses.json").read_text())
        artifact = json.loads(
            (ignition_dir / "artifacts" / f"{module_id}.json").read_text()
        )
        address = Web3.to_checksum_address(addresses[module_id])
        return address, artifact["abi"]
    except (OSError, KeyError, TypeError, ValueError) as exc:
        raise BlockchainSubmissionError(
            f"Could not load deployment {module_id!r} from {ignition_dir}"
        ) from exc


class SepoliaClaimsRegistry:
    """Sign and submit claims using one Sepolia-only demonstration wallet."""

    def __init__(
        self,
        *,
        rpc_url: str,
        private_key: str,
        ignition_dir: Path = DEFAULT_IGNITION_DIR,
        module_id: str = DEFAULT_MODULE_ID,
        receipt_timeout: int = 180,
    ) -> None:
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))
        if not self.w3.is_connected():
            raise BlockchainSubmissionError(
                "Could not connect to the configured Ethereum RPC endpoint"
            )
        if self.w3.eth.chain_id != SEPOLIA_CHAIN_ID:
            raise BlockchainSubmissionError(
                f"Expected Sepolia chain {SEPOLIA_CHAIN_ID}, got {self.w3.eth.chain_id}"
            )

        address, abi = load_deployment(ignition_dir, module_id)
        self.contract = self.w3.eth.contract(address=address, abi=abi)
        try:
            self.account = self.w3.eth.account.from_key(private_key)
        except Exception as exc:
            raise BlockchainSubmissionError(
                "SEPOLIA_PRIVATE_KEY is not a valid Ethereum private key"
            ) from exc
        self.receipt_timeout = receipt_timeout
        self._submission_lock = threading.Lock()
        self._next_nonce: int | None = None

    @classmethod
    def from_env(cls) -> "SepoliaClaimsRegistry":
        rpc_url = os.environ.get("SEPOLIA_RPC_URL") or os.environ.get("RPC_URL")
        private_key = os.environ.get("SEPOLIA_PRIVATE_KEY")
        missing = [
            name
            for name, value in (
                ("SEPOLIA_RPC_URL", rpc_url),
                ("SEPOLIA_PRIVATE_KEY", private_key),
            )
            if not value
        ]
        if missing:
            raise BlockchainSubmissionError(
                f"Missing required environment variable(s): {', '.join(missing)}"
            )

        return cls(
            rpc_url=rpc_url,
            private_key=private_key,
            ignition_dir=Path(
                os.environ.get("IGNITION_DIR", str(DEFAULT_IGNITION_DIR))
            ),
            module_id=os.environ.get("MODULE_ID", DEFAULT_MODULE_ID),
            receipt_timeout=int(os.environ.get("RECEIPT_TIMEOUT", "180")),
        )

    def submit_claim(self, claim_hash: bytes, data_pointer: str) -> ChainSubmission:
        """Submit a claim and recover its assigned ID from the emitted event."""

        try:
            # Serializing wallet use prevents two API threads allocating one nonce.
            with self._submission_lock:
                if self._next_nonce is None:
                    self._next_nonce = self.w3.eth.get_transaction_count(
                        self.account.address, "pending"
                    )

                for attempt in range(2):
                    nonce = self._next_nonce
                    transaction = self.contract.functions.submitClaim(
                        claim_hash, data_pointer
                    ).build_transaction(
                        {
                            "from": self.account.address,
                            "nonce": nonce,
                            "chainId": SEPOLIA_CHAIN_ID,
                        }
                    )
                    signed = self.account.sign_transaction(transaction)
                    try:
                        transaction_hash = self.w3.eth.send_raw_transaction(
                            signed.raw_transaction
                        )
                    except Web3RPCError as exc:
                        match = re.search(
                            r"next nonce\s+(\d+)", str(exc), re.IGNORECASE
                        )
                        if attempt == 0 and match and int(match.group(1)) > nonce:
                            self._next_nonce = int(match.group(1))
                            continue
                        self._next_nonce = None
                        raise

                    self._next_nonce = nonce + 1
                    break

                receipt = self.w3.eth.wait_for_transaction_receipt(
                    transaction_hash, timeout=self.receipt_timeout
                )

            if receipt["status"] != 1:
                raise BlockchainSubmissionError(
                    f"Sepolia transaction reverted: {_hex(transaction_hash)}"
                )

            events = self.contract.events.ClaimSubmitted().process_receipt(receipt)
            if len(events) != 1:
                raise BlockchainSubmissionError(
                    "Transaction did not emit exactly one ClaimSubmitted event"
                )

            return ChainSubmission(
                claim_id=events[0]["args"]["claimId"],
                transaction_hash=_hex(transaction_hash),
                block_number=receipt["blockNumber"],
            )
        except BlockchainSubmissionError:
            raise
        except Exception as exc:
            self._next_nonce = None
            raise BlockchainSubmissionError(f"Sepolia submission failed: {exc}") from exc
