"""Keep all Sepolia-specific behaviour behind one small Python adapter.

The service layer should be able to talk in terms of claims and assessments
without knowing about nonces, ABI files, receipts, or event decoding. This file
owns those details and checks each write rather than treating a submitted
transaction hash as proof that the contract accepted it.
"""

from __future__ import annotations

import json
import os
import re
import threading
from dataclasses import dataclass
from pathlib import Path

from web3 import Web3
from web3.exceptions import Web3RPCError


SEPOLIA_CHAIN_ID = 11_155_111
DEFAULT_MODULE_ID = "ClaimsRegistryModule#ClaimsRegistry"
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_IGNITION_DIR = (
    PROJECT_ROOT / "contract" / "ignition" / "deployments" / "chain-11155111"
)


class BlockchainSubmissionError(RuntimeError):
    """Raised when a claim cannot be committed to the registry."""


@dataclass(frozen=True)
class ChainSubmission:
    claim_id: int
    transaction_hash: str
    block_number: int


@dataclass(frozen=True)
class ChainAssessment:
    transaction_hash: str
    block_number: int
    status: int
    fraud_score: int


@dataclass(frozen=True)
class ChainClaim:
    claim_id: int
    claimant: str
    claim_hash: str
    data_pointer: str
    status: int
    fraud_score: int
    submitted_at: int
    updated_at: int


def _hex(value: object) -> str:
    encoded = value.hex()  # type: ignore[union-attr]
    return encoded if encoded.startswith("0x") else f"0x{encoded}"


def load_deployment(
    ignition_dir: Path, module_id: str = DEFAULT_MODULE_ID
) -> tuple[str, list[dict[str, object]]]:
    """Load the address and ABI generated by Hardhat Ignition."""

    try:
        addresses = json.loads((ignition_dir / "deployed_addresses.json").read_text())
        artifact = json.loads(
            (ignition_dir / "artifacts" / f"{module_id}.json").read_text()
        )
        address = Web3.to_checksum_address(addresses[module_id])
        return address, artifact["abi"]
    except (OSError, KeyError, TypeError, ValueError) as exc:
        raise BlockchainSubmissionError(
            f"Could not load deployment {module_id!r} from {ignition_dir}"
        ) from exc


class SepoliaClaimsRegistry:
    """Read the registry and optionally sign writes with a testnet wallet."""

    def __init__(
        self,
        *,
        rpc_url: str,
        private_key: str | None,
        ignition_dir: Path = DEFAULT_IGNITION_DIR,
        module_id: str = DEFAULT_MODULE_ID,
        receipt_timeout: int = 180,
        private_key_env: str = "SEPOLIA_SUBMITTER_PRIVATE_KEY",
    ) -> None:
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))

        # Stop early if the RPC is offline or points to the wrong network. This
        # prevents a claim from being sent somewhere unexpected.
        if not self.w3.is_connected():
            raise BlockchainSubmissionError(
                "Could not connect to the configured Ethereum RPC endpoint"
            )
        if self.w3.eth.chain_id != SEPOLIA_CHAIN_ID:
            raise BlockchainSubmissionError(
                f"Expected Sepolia chain {SEPOLIA_CHAIN_ID}, got {self.w3.eth.chain_id}"
            )

        address, abi = load_deployment(ignition_dir, module_id)
        self.contract = self.w3.eth.contract(address=address, abi=abi)

        # Public reads need only the RPC endpoint and deployed contract address.
        # The query-only FastAPI dependency deliberately passes no key, keeping
        # signing authority out of a code path that can never submit a write.
        self.account = None
        self.private_key_env = private_key_env
        if private_key is not None:
            try:
                self.account = self.w3.eth.account.from_key(private_key)
            except Exception as exc:
                raise BlockchainSubmissionError(
                    f"{private_key_env} is not a valid Ethereum private key"
                ) from exc
        self.receipt_timeout = receipt_timeout
        # Ethereum accepts each wallet nonce only once. FastAPI and the worker can
        # issue writes close together, so keep nonce allocation inside one lock
        # instead of letting two requests accidentally build the same transaction.
        self._submission_lock = threading.Lock()
        self._next_nonce: int | None = None

    @classmethod
    def from_env(
        cls,
        *,
        require_private_key: bool = True,
        private_key_env: str = "SEPOLIA_SUBMITTER_PRIVATE_KEY",
    ) -> "SepoliaClaimsRegistry":
        """Create either a read-only client or a transaction-capable client.

        Write callers use the safe default and must provide a wallet. Public
        query callers explicitly opt out, and the environment key is not even
        loaded into that client.
        """

        rpc_url = os.environ.get("SEPOLIA_RPC_URL") or os.environ.get("RPC_URL")
        private_key = (
            os.environ.get(private_key_env) if require_private_key else None
        )
        missing = [
            name
            for name, value in (
                ("SEPOLIA_RPC_URL", rpc_url),
                (
                    private_key_env,
                    private_key if require_private_key else "not-required",
                ),
            )
            if not value
        ]
        if missing:
            raise BlockchainSubmissionError(
                f"Missing required environment variable(s): {', '.join(missing)}"
            )

        return cls(
            rpc_url=rpc_url,
            private_key=private_key,
            ignition_dir=Path(
                os.environ.get("IGNITION_DIR", str(DEFAULT_IGNITION_DIR))
            ),
            module_id=os.environ.get("MODULE_ID", DEFAULT_MODULE_ID),
            receipt_timeout=int(os.environ.get("RECEIPT_TIMEOUT", "180")),
            private_key_env=private_key_env,
        )

    def _signing_account(self):
        """Return the configured signer or fail before constructing a write."""

        if self.account is None:
            raise BlockchainSubmissionError(
                f"{self.private_key_env} is required for blockchain writes"
            )
        return self.account

    def submit_claim(self, claim_hash: bytes, data_pointer: str) -> ChainSubmission:
        """Submit a claim and read its new ID from the contract event."""

        try:
            account = self._signing_account()
            with self._submission_lock:
                if self._next_nonce is None:
                    self._next_nonce = self.w3.eth.get_transaction_count(
                        account.address, "pending"
                    )

                for attempt in range(2):
                    nonce = self._next_nonce
                    transaction = self.contract.functions.submitClaim(
                        claim_hash, data_pointer
                    ).build_transaction(
                        {
                            "from": account.address,
                            "nonce": nonce,
                            "chainId": SEPOLIA_CHAIN_ID,
                        }
                    )
                    signed = account.sign_transaction(transaction)
                    try:
                        transaction_hash = self.w3.eth.send_raw_transaction(
                            signed.raw_transaction
                        )
                    except Web3RPCError as exc:
                        # A public RPC can briefly report an old nonce. If it tells
                        # us the newer one, retry once instead of failing the claim.
                        match = re.search(
                            r"next nonce\s+(\d+)", str(exc), re.IGNORECASE
                        )
                        if attempt == 0 and match and int(match.group(1)) > nonce:
                            self._next_nonce = int(match.group(1))
                            continue
                        self._next_nonce = None
                        raise

                    self._next_nonce = nonce + 1
                    break

                receipt = self.w3.eth.wait_for_transaction_receipt(
                    transaction_hash, timeout=self.receipt_timeout
                )

            if receipt["status"] != 1:
                raise BlockchainSubmissionError(
                    f"Sepolia transaction reverted: {_hex(transaction_hash)}"
                )

            # A successful receipt says the transaction ran, while the event tells
            # us which claim ID the contract actually assigned to this submission.
            events = self.contract.events.ClaimSubmitted().process_receipt(receipt)
            if len(events) != 1:
                raise BlockchainSubmissionError(
                    "Transaction did not emit exactly one ClaimSubmitted event"
                )

            return ChainSubmission(
                claim_id=events[0]["args"]["claimId"],
                transaction_hash=_hex(transaction_hash),
                block_number=receipt["blockNumber"],
            )
        except BlockchainSubmissionError:
            raise
        except Exception as exc:
            self._next_nonce = None
            raise BlockchainSubmissionError(
                f"Sepolia submission failed: {exc}"
            ) from exc

    def assess_claim(
        self, claim_id: int, status: int, fraud_score: int
    ) -> ChainAssessment:
        """Write the model result and confirm the contract recorded it."""

        if status not in range(5):
            raise BlockchainSubmissionError(f"Invalid claim status: {status}")
        if fraud_score not in range(10_001):
            raise BlockchainSubmissionError(
                f"Fraud score must be between 0 and 10000, got {fraud_score}"
            )

        try:
            account = self._signing_account()
            with self._submission_lock:
                if self._next_nonce is None:
                    self._next_nonce = self.w3.eth.get_transaction_count(
                        account.address, "pending"
                    )

                for attempt in range(2):
                    nonce = self._next_nonce
                    transaction = self.contract.functions.assessClaim(
                        claim_id, status, fraud_score
                    ).build_transaction(
                        {
                            "from": account.address,
                            "nonce": nonce,
                            "chainId": SEPOLIA_CHAIN_ID,
                        }
                    )
                    signed = account.sign_transaction(transaction)
                    try:
                        transaction_hash = self.w3.eth.send_raw_transaction(
                            signed.raw_transaction
                        )
                    except Web3RPCError as exc:
                        # Use the same one-time stale nonce recovery as submission.
                        match = re.search(
                            r"next nonce\s+(\d+)", str(exc), re.IGNORECASE
                        )
                        if attempt == 0 and match and int(match.group(1)) > nonce:
                            self._next_nonce = int(match.group(1))
                            continue
                        self._next_nonce = None
                        raise

                    self._next_nonce = nonce + 1
                    break

                receipt = self.w3.eth.wait_for_transaction_receipt(
                    transaction_hash, timeout=self.receipt_timeout
                )

            if receipt["status"] != 1:
                raise BlockchainSubmissionError(
                    f"Sepolia assessment reverted: {_hex(transaction_hash)}"
                )

            events = self.contract.events.ClaimAssessed().process_receipt(receipt)
            if len(events) != 1:
                raise BlockchainSubmissionError(
                    "Transaction did not emit exactly one ClaimAssessed event"
                )
            # Do not trust only the transaction status. Check that the event data
            # contains the claim, status, and score we asked the contract to save.
            event = events[0]["args"]
            if (
                event["claimId"] != claim_id
                or event["newStatus"] != status
                or event["fraudScore"] != fraud_score
            ):
                raise BlockchainSubmissionError(
                    "ClaimAssessed event did not match the requested assessment"
                )

            return ChainAssessment(
                transaction_hash=_hex(transaction_hash),
                block_number=receipt["blockNumber"],
                status=status,
                fraud_score=fraud_score,
            )
        except BlockchainSubmissionError:
            raise
        except Exception as exc:
            self._next_nonce = None
            raise BlockchainSubmissionError(
                f"Sepolia assessment failed: {exc}"
            ) from exc

    def list_claims(
        self, *, page: int, page_size: int
    ) -> tuple[list[ChainClaim], int]:
        """Read one small page directly from the contract, newest claim first."""

        try:
            claim_count = self.contract.functions.claimCount().call()
            claims: list[ChainClaim] = []
            # Claim IDs grow from zero. Walking backwards avoids reading the whole
            # registry just to render one dashboard page. A production application
            # would normally serve this view from an event index instead.
            first_claim_id = claim_count - 1 - ((page - 1) * page_size)
            if first_claim_id < 0:
                return claims, claim_count

            final_claim_id = max(first_claim_id - page_size + 1, 0)
            for claim_id in range(first_claim_id, final_claim_id - 1, -1):
                claim = self.contract.functions.getClaim(claim_id).call()
                claims.append(
                    ChainClaim(
                        claim_id=claim_id,
                        claimant=Web3.to_checksum_address(claim[0]),
                        claim_hash=_hex(claim[1]),
                        data_pointer=claim[2],
                        status=claim[3],
                        fraud_score=claim[4],
                        submitted_at=claim[5],
                        updated_at=claim[6],
                    )
                )
            return claims, claim_count
        except Exception as exc:
            raise BlockchainSubmissionError(
                f"Could not read claims from Sepolia: {exc}"
            ) from exc

    def get_claim(self, claim_id: int) -> ChainClaim:
        """Read one claim so an at-least-once worker can avoid a second write."""

        try:
            claim = self.contract.functions.getClaim(claim_id).call()
            return ChainClaim(
                claim_id=claim_id,
                claimant=Web3.to_checksum_address(claim[0]),
                claim_hash=_hex(claim[1]),
                data_pointer=claim[2],
                status=claim[3],
                fraud_score=claim[4],
                submitted_at=claim[5],
                updated_at=claim[6],
            )
        except Exception as exc:
            raise BlockchainSubmissionError(
                f"Could not read claim {claim_id} from Sepolia: {exc}"
            ) from exc
